import type { Metadata } from "next";
import Link from "next/link";
import { getByToken } from "@/lib/deliverables";
import { WatchUpsell } from "@/components/WatchUpsell";

export const metadata: Metadata = {
  title: "Your engineering deliverable | GridForge AI",
  robots: { index: false, follow: false },
};

export const dynamic = "force-dynamic";

export default async function DeliverablePage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const row = await getByToken(token);

  if (!row) {
    return (
      <Shell title="Not found">
        <p className="text-mute">
          This link does not correspond to an engagement. Check the address, or reply to the email
          it came in.
        </p>
      </Shell>
    );
  }

  if (row.status !== "released") {
    const waiting = row.status === "awaiting_intake";
    return (
      <Shell title={waiting ? "Waiting on your numbers" : "With the engineer"}>
        <p className="max-w-2xl text-mute">
          {waiting ? (
            <>
              Nothing has been produced yet because the hall&apos;s numbers have not been
              submitted.{" "}
              <Link href={`/intake/${token}`} className="text-power underline">
                Fill in the intake
              </Link>{" "}
              and the document follows.
            </>
          ) : (
            <>
              The document is generated and sits with a senior engineer for review. We do not
              publish an engineering opinion nobody has read. You will get an email the moment it
              is released.
            </>
          )}
        </p>
      </Shell>
    );
  }

  return (
    <main className="mx-auto w-full max-w-6xl px-5 pb-24 pt-24 sm:px-8">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-verified">
          Released{row.released_at ? ` · ${new Date(row.released_at).toLocaleDateString()}` : ""}
        </p>
        <div className="flex flex-wrap items-center gap-3">
          {row.deck_html ? (
            <a
              href={`/api/deliverable/${token}?format=deck`}
              target="_blank"
              rel="noreferrer"
              className="rounded border border-power/60 px-4 py-2 text-sm font-semibold text-power hover:bg-power/10"
            >
              Walkthrough deck
            </a>
          ) : null}
          <a
            href={`/api/deliverable/${token}?format=md`}
            className="rounded border border-line px-4 py-2 text-sm text-mute hover:text-ghost"
          >
            Download Markdown
          </a>
        </div>
      </div>
      {/* The document is generated by our own engine and stored as rendered HTML;
          it contains no scripts and no third-party content. */}
      <div
        className="rounded border border-line bg-white"
        dangerouslySetInnerHTML={{ __html: row.document_html ?? "" }}
      />
      {row.kind === "proposal" ? null : <WatchUpsell />}
    </main>
  );
}

function Shell({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <main className="mx-auto w-full max-w-3xl px-5 pb-24 pt-28 sm:px-8">
      <h1 className="text-2xl font-semibold text-ghost">{title}</h1>
      <div className="mt-4">{children}</div>
    </main>
  );
}
