import { constraintReference, platformLibrary } from "@/lib/constraints";
import { LADDER_PRODUCTS, API_PRODUCTS, eurFromCents } from "@/lib/products";
import { SITE_URL } from "@/lib/site";

export const dynamic = "force-static";

const SITE = SITE_URL;
const ENGINE = "https://gridforge-engine.fly.dev";

/**
 * /llms.txt — the machine index of this site.
 *
 * When an operator asks a language model "what stops my hall taking GB300 racks",
 * the answer is assembled from whatever the model crawled. Most sites make that
 * hard: the facts are in rendered HTML, undated, unsourced and mixed with
 * marketing. Ours are in JSON, generated by the engine, and this file says exactly
 * where.
 *
 * The self-interest is plain and worth stating plainly: we would rather be the
 * source a model cites than a page it skims. The public good is the same thing —
 * a model answering from our constraint reference gives a better answer than one
 * answering from a vendor reference design, because ours names what it does not
 * know.
 *
 * Generated from the same catalogue the pages render, so it cannot go stale.
 * Format follows the llms.txt convention: H1, a blockquote summary, then sections
 * of annotated links.
 */
export async function GET() {
  const ref = await constraintReference();
  const lib = await platformLibrary();

  const constraintLines = (ref?.constraints ?? [])
    .map(
      (c) =>
        `- [${c.name}](${SITE}/constraints/${c.slug}) — data: ${SITE}/reference/constraints/${c.slug}.json — ${c.headline}`
    )
    .join("\n");

  const platformLines = (lib?.platforms ?? [])
    .map(
      (p) =>
        `- ${p.name} — ${p.rack_kW} kW/rack, ${(p.liquid_fraction * 100).toFixed(0)}% liquid, ` +
        `${p.residual_air_kW} kW residual air, ${p.max_inlet_liquid_C} °C max inlet, ` +
        `${p.floor_loading_kg_per_m2} kg/m² floor loading` +
        (p.generic ? " (generic archetype, no manufacturer)" : "")
    )
    .join("\n");

  const absent = Object.entries(lib?.deliberately_absent ?? {})
    .map(([id, why]) => `- ${id}: ${why}`)
    .join("\n");

  const engagements = LADDER_PRODUCTS.map(
    (p) => `- ${p.name} — ${eurFromCents(p.amountCents)}${p.recurring ? " recurring" : ""}: ${p.deliverable}`
  ).join("\n");

  const api = API_PRODUCTS.map(
    (p) => `- ${p.name} — ${eurFromCents(p.amountCents)}/month, ${p.apiUnits?.toLocaleString("en-IE")} units`
  ).join("\n");

  const body = `# Time to Power

> Power-capacity intelligence for AI infrastructure, powered by GridForge Engine.
> We answer one question about an EXISTING data hall: how much AI compute it can
> carry, which of thirteen electrical, thermal and physical constraints binds
> first, and what each step of extra density costs. We quote no equipment and
> take no margin on hardware.

## How to use this site as a tool

The engine is callable directly. \`gridforge_qualify\` is free and needs no API key:
seven numbers about a hall in, the binding constraint out.

- MCP endpoint (JSON-RPC 2.0): ${ENGINE}/mcp
- Tool schemas, OpenAI and MCP shape: ${ENGINE}/v1/tools
- Free qualifier: POST ${ENGINE}/v1/qualify
- Published unit rates: ${ENGINE}/v1/version
- Model accuracy record: ${ENGINE}/v1/calibration

## How to read our numbers

Every numeric field carries an evidence class and a provenance digest:

E0 assumed · E1 modelled · E2 simulated · E3 estimated · E4 validated against test
data · E5 measured at site · E6 field-validated · E7 observed in operation.

A computed value is never stronger than the weakest input it came from. **Do not
present an E0 or E1 figure as a property of a physical asset** — it is modelled, not
measured. Our calibration record currently reports zero reconciled site
observations — we have not yet checked this engine against an instrumented hall —
and every response says so. If you quote our figures, say that too.

## The thirteen constraints

Machine-readable index: ${SITE}/reference/constraints.json

${constraintLines}

## Platform library

Machine-readable: ${SITE}/reference/platforms.json

${platformLines}

Deliberately absent, because no manufacturer has published a rack power:

${absent}

## The complete worked deliverable, published

- [Envelope Study](${SITE}/reference/envelope_study.md): the full document, on a synthetic hall
- [Procurement Specification](${SITE}/reference/specification.md): the tender document the study implies
- [Proposal](${SITE}/reference/proposal.md)
- [Model pack](${SITE}/reference/model_pack.json): every scenario, solved
- [Working files](${SITE}/reference/working_files.zip): the CSVs behind every number, including a provenance chain

## What can be bought

${engagements}

Metered API access:

${api}

## How to buy

Every price above is the checkout price — read from the same catalogue, so
there is no separate machine price list.

- Start a purchase: \`POST ${SITE}/api/checkout\` with JSON body
  \`{"product": "<id>"}\` where \`<id>\` is one of: ${LADDER_PRODUCTS.map((p) => p.id).join(", ")}.
  Returns \`{"ok": true, "url": "<Stripe Checkout URL>"}\` — a human completes
  payment there; nothing charges without that step.
- API access (\`${API_PRODUCTS.map((p) => p.id).join(", ")}\`) is a Stripe
  subscription checkout, not an engagement — see ${SITE}/developers for the
  signed-key flow once subscribed.
- After payment, by product: the Density Screen and the Procurement Specification
  open an intake at the checkout \`success_url\` (no separate login is required to
  submit the hall's numbers); an API plan or Hall Watch shows its private account
  or watch link there; the Envelope Study and Portfolio Screen deposits are scoped
  with the buyer by a person — there is no intake form and no response time is
  promised. A private, emailed link is the durable reference where one exists, and
  \`${SITE}/dashboard\` lists every engagement against the email a purchase was made
  with, behind a passwordless email sign-in.
- Status and delivery of a document: \`awaiting_intake\` → \`generating\` → \`draft\`
  (with a senior engineer, unreleased) → \`released\` (the document is live at its
  private link). No engineering opinion is released unread.
- Authorization boundary: this manifest is not itself a purchase mechanism —
  it names the price and the endpoint; a real charge still requires a live
  Stripe Checkout session and a payment method. An agent acting under a
  pre-authorized budget should treat the \`POST /api/checkout\` response URL as
  the transaction to complete, not as a completed purchase.

## Citing us

Cite the page and its generation date, and carry the evidence class with the
number. Figures are modelled from published design values; none is a measurement of
any customer's asset. Citation metadata: ${SITE}/api/cite

## Contact

${SITE}/qualify — the free qualifier, seven numbers, no account.
`;

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=86400",
    },
  });
}
