import fs from "node:fs/promises";
import path from "node:path";
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Boxes, Gauge, ShieldCheck, Terminal } from "lucide-react";
import ApiPlans from "@/components/ApiPlans";
import McpInstall from "@/components/McpInstall";

export const metadata: Metadata = {
  title: "Machine interface — call the engine | GridForge AI",
  description:
    "The GridForge capacity and thermal envelope engine as a tool your software can call: JSON over HTTPS, MCP for agents, published unit pricing, and an evidence class on every number.",
};

/**
 * The machine interface.
 *
 * The people who need this answer are increasingly not people. A colo operator's
 * portfolio team runs an agent over two hundred halls; a fund's diligence stack
 * wants the binding constraint before it bids. None of them will read a PDF.
 *
 * Everything rendered here comes from public/reference/tools.json, which is
 * generated by the engine itself and diffed in CI — so the schema an integrator
 * reads is the schema the server validates against, not a hand-written copy of it
 * that drifted two releases ago.
 */

interface Tool {
  name: string;
  description: string;
  endpoint: string;
  units: number;
  tier: string;
  returns: string;
}

interface Catalogue {
  tools: Tool[];
  mcp: { endpoint: string; protocolVersion: string };
  auth: { header: string; note: string };
  evidence_note: string;
}

interface Accuracy {
  state: string;
  statement: string;
  observations: number;
  sites: number;
  keys_asserted: number;
  keys_with_site_observations: number;
}

async function readJson<T>(file: string): Promise<T | null> {
  try {
    const raw = await fs.readFile(
      path.join(process.cwd(), "public", "reference", file),
      "utf8"
    );
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

const API = "https://gridforge-engine.fly.dev";

export default async function DevelopersPage() {
  const cat = await readJson<Catalogue>("tools.json");
  const acc = await readJson<Accuracy>("calibration.json");
  const tools = cat?.tools ?? [];

  return (
    <main className="mx-auto w-full max-w-6xl px-5 pb-24 pt-28 sm:px-8">
      <header className="max-w-3xl">
        <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-power">
          Machine interface · JSON, MCP, metered
        </p>
        <h1 className="mt-3 text-3xl font-semibold leading-tight text-ghost sm:text-4xl">
          Your software can ask what binds, and get an engineering answer back.
        </h1>
        <p className="mt-4 text-mute">
          The same engine behind the studies, callable directly. Thirteen electrical, thermal and
          physical constraints solved against a hall; the binding one returned with its basis, the
          costed relief ladder behind it, and the date the whole thing turns on. No account
          manager, no PDF, no spreadsheet round-trip.
        </p>
        <div className="mt-6 flex flex-wrap gap-3">
          <a
            href={`${API}/v1/tools`}
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-2 rounded border border-line px-5 py-2.5 font-semibold text-ghost hover:border-power/50"
          >
            Tool schemas <ArrowRight className="h-4 w-4" />
          </a>
          <a
            href="#plans"
            className="inline-flex items-center gap-2 rounded bg-power px-5 py-2.5 font-semibold text-ink"
          >
            Get a key <ArrowRight className="h-4 w-4" />
          </a>
          <a
            href="/reference/tools.json"
            className="inline-flex items-center gap-2 rounded border border-line px-5 py-2.5 font-semibold text-ghost hover:border-power/50"
          >
            Download the catalogue
          </a>
        </div>
      </header>

      <section className="mt-12 grid gap-4 md:grid-cols-3">
        <Pill
          icon={<Terminal className="h-4 w-4" />}
          title="Two dialects, one definition"
          body="OpenAI / Anthropic function-calling shape at /v1/tools, and Model Context Protocol over JSON-RPC at /mcp. Both generated from the same schema the server validates against."
        />
        <Pill
          icon={<Gauge className="h-4 w-4" />}
          title="Units, not calls"
          body="A qualify and a forty-hall portfolio run do not cost the same and are not billed the same. Rates are published at /v1/version so you can price a job before you run it."
        />
        <Pill
          icon={<ShieldCheck className="h-4 w-4" />}
          title="Evidence on every number"
          body="Each figure carries an evidence class E0–E7 and a provenance digest. A modelled number loose inside an agent loop is more dangerous than one in a board pack, not less."
        />
      </section>

      <section className="mt-12">
        <h2 className="text-xl font-semibold text-ghost">What you can call</h2>
        <p className="mt-2 max-w-3xl text-sm text-mute">
          {cat?.auth.note ??
            "gridforge_qualify is free and needs no key. Everything else meters."}
        </p>
        <div className="mt-5 overflow-x-auto">
          <table className="w-full min-w-[720px] border-collapse text-sm">
            <thead>
              <tr className="border-b border-line text-left font-mono text-[10px] uppercase tracking-[0.14em] text-faint">
                <th className="py-2 pr-4">Tool</th>
                <th className="py-2 pr-4">Endpoint</th>
                <th className="py-2 pr-4 text-right">Units</th>
                <th className="py-2">Returns</th>
              </tr>
            </thead>
            <tbody>
              {tools.map((t) => (
                <tr key={t.name} className="border-b border-line/60 align-top">
                  <td className="py-3 pr-4 font-mono text-xs text-ghost">
                    {t.name}
                    {t.tier === "public" ? (
                      <span className="ml-2 rounded bg-verified/15 px-1.5 py-0.5 text-[10px] text-verified">
                        free
                      </span>
                    ) : null}
                  </td>
                  <td className="py-3 pr-4 font-mono text-xs text-mute">{t.endpoint}</td>
                  <td className="py-3 pr-4 text-right font-mono text-xs text-power">{t.units}</td>
                  <td className="py-3 text-xs text-mute">{t.returns}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mt-12">
        <McpInstall engine={API} />
      </section>

      <section className="mt-6 grid gap-4 lg:grid-cols-2">
        <div className="rounded border border-line bg-panel-2 p-6">
          <h3 className="text-lg font-semibold text-ghost">Try it without a key</h3>
          <p className="mt-2 text-sm text-mute">
            Seven numbers about an existing air-cooled hall. The answer names the constraint that
            binds first, how many racks fit as found, and which item sets the energisation date.
          </p>
          <pre className="mt-4 overflow-x-auto rounded bg-ink p-4 font-mono text-[11px] leading-relaxed text-mute">
{`curl -s -X POST ${API}/v1/qualify \\
  -H 'content-type: application/json' \\
  -d '{"contracted_MW":12,
       "current_site_peak_MW":7.4,
       "current_it_load_MW":4.9,
       "busway_ampacity_A":400,
       "tapoff_max_A":63,
       "plant_supply_C":6,
       "positions_available":180}'`}
          </pre>
        </div>
        <div className="rounded border border-line bg-panel-2 p-6">
          <h3 className="text-lg font-semibold text-ghost">Point an agent at it</h3>
          <p className="mt-2 text-sm text-mute">
            MCP over JSON-RPC 2.0 at{" "}
            <span className="font-mono text-ghost">{cat?.mcp.endpoint ?? "/mcp"}</span>, protocol{" "}
            <span className="font-mono text-ghost">
              {cat?.mcp.protocolVersion ?? "2025-06-18"}
            </span>
            . The transport is open; each tool keeps its own tier, so the free qualifier works
            without a key and everything else asks for one.
          </p>
          <pre className="mt-4 overflow-x-auto rounded bg-ink p-4 font-mono text-[11px] leading-relaxed text-mute">
{`curl -s -X POST ${API}/mcp \\
  -H 'x-api-key: YOUR_KEY' \\
  -H 'content-type: application/json' \\
  -d '{"jsonrpc":"2.0","id":1,
       "method":"tools/call",
       "params":{"name":"gridforge_qualify",
                 "arguments":{ ... }}}'`}
          </pre>
        </div>
      </section>

      <section className="mt-12 rounded border border-line bg-panel-2 p-6">
        <div className="flex items-start gap-3">
          <Boxes className="mt-0.5 h-4 w-4 shrink-0 text-power" />
          <div className="max-w-3xl">
            <h2 className="text-lg font-semibold text-ghost">
              What the engine says about its own accuracy
            </h2>
            <p className="mt-2 text-sm text-mute">{acc?.statement}</p>
            <div className="mt-4 grid gap-3 sm:grid-cols-4">
              <Stat k="State" v={acc?.state ?? "—"} />
              <Stat k="Observations" v={String(acc?.observations ?? 0)} />
              <Stat k="Sites" v={String(acc?.sites ?? 0)} />
              <Stat
                k="Outputs covered"
                v={`${acc?.keys_with_site_observations ?? 0}/${acc?.keys_asserted ?? 0}`}
              />
            </div>
            <p className="mt-4 text-[11px] text-faint">
              This block is on every response, including the free one, including while the answer
              is zero. An accuracy record that only appears once it flatters us is a marketing
              number. Live at{" "}
              <a
                href={`${API}/v1/calibration`}
                target="_blank"
                rel="noreferrer"
                className="font-mono text-power"
              >
                /v1/calibration
              </a>
              .
            </p>
          </div>
        </div>
      </section>

      {cat ? (
        <section className="mt-8 rounded border border-queue/40 bg-queue/10 p-6">
          <span className="font-mono text-[11px] uppercase tracking-[0.12em] text-queue">
            If you are integrating this
          </span>
          <p className="mt-2 max-w-3xl text-sm text-mute">{cat.evidence_note}</p>
        </section>
      ) : null}

      <section id="plans" className="mt-12 scroll-mt-24">
        <h2 className="text-xl font-semibold text-ghost">Metered access</h2>
        <p className="mt-2 max-w-3xl text-sm text-mute">
          Run the free qualifier first — if it answers your question you do not need a key. If
          you have two hundred halls and a model that needs re-running every time a tariff or a
          platform spec moves, this is what that costs.
        </p>
        <div className="mt-6">
          <ApiPlans />
        </div>
      </section>

      <section className="mt-10 flex flex-wrap items-center gap-4 rounded border border-line bg-panel-2 p-6">
        <div className="min-w-64 flex-1">
          <h2 className="text-lg font-semibold text-ghost">Not sure yet?</h2>
          <p className="mt-1 text-sm text-mute">
            The qualifier is free and needs no key, and the full deliverable is published in
            full — document, deck, proposal and the tables behind every number.
          </p>
        </div>
        <Link
          href="/qualify"
          className="inline-flex items-center gap-2 rounded border border-line px-5 py-2.5 font-semibold text-ghost hover:border-power/50"
        >
          Run the free qualifier <ArrowRight className="h-4 w-4" />
        </Link>
        <Link
          href="/reference"
          className="inline-flex items-center gap-2 rounded border border-line px-5 py-2.5 font-semibold text-ghost hover:border-power/50"
        >
          See the full deliverable
        </Link>
      </section>
    </main>
  );
}

function Pill({
  icon,
  title,
  body,
}: {
  icon: React.ReactNode;
  title: string;
  body: string;
}) {
  return (
    <div className="panel flex flex-col p-5">
      <span className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.14em] text-power">
        {icon}
        {title}
      </span>
      <p className="mt-3 text-sm text-mute">{body}</p>
    </div>
  );
}

function Stat({ k, v }: { k: string; v: string }) {
  return (
    <div className="rounded border border-line bg-panel px-3 py-2">
      <p className="font-mono text-[10px] uppercase tracking-[0.14em] text-faint">{k}</p>
      <p className="mt-1 font-mono text-lg font-semibold text-ghost">{v}</p>
    </div>
  );
}
