import fs from "node:fs/promises";
import path from "node:path";
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, FileText, Presentation, Table2 } from "lucide-react";

export const metadata: Metadata = {
  title: "The deliverable, in full — worked example | GridForge AI",
  description:
    "Read the exact document a Capacity & Density Envelope Study produces, on a synthetic European colocation hall. The headroom ladder, time to power, the economics, and the working files behind every number.",
};

/**
 * The worked example.
 *
 * Buyers of engineering work are asked to pay five figures for something they
 * have never seen. This page removes that: the actual deliverable, in full,
 * generated by the same engine on a synthetic hall — including the tables behind
 * it, so a sceptical engineer can check the arithmetic before spending anything.
 *
 * Everything here is regenerated by scripts/build-reference.sh and CI fails if the
 * committed files differ from a fresh run. A worked example that has drifted from
 * the engine is a promise we no longer keep.
 */

interface Pack {
  scenarios: {
    id: string;
    name: string;
    as_found: { racks: number; binding_name: string; basis: string };
    after_ladder: { racks: number };
    time_to_power: { weeks_to_full: number | null; sets_the_date: string };
    economics: { capex_total_eur: { value: number } | null };
  }[];
  intake: { completeness: number; gaps: unknown[] };
}

async function readPack(): Promise<Pack | null> {
  try {
    const raw = await fs.readFile(
      path.join(process.cwd(), "public", "reference", "model_pack.json"),
      "utf8"
    );
    return JSON.parse(raw) as Pack;
  } catch {
    return null;
  }
}

const eur = (n: number) =>
  new Intl.NumberFormat("en-IE", {
    style: "currency",
    currency: "EUR",
    maximumFractionDigits: 0,
  }).format(n);

export default async function ReferencePage() {
  const pack = await readPack();
  const best = pack?.scenarios?.reduce((a, b) =>
    b.after_ladder.racks > a.after_ladder.racks ? b : a
  );
  const gridOnly = pack?.scenarios?.find((s) => s.id === "full_dlc");

  return (
    <main className="mx-auto w-full max-w-6xl px-5 pb-24 pt-28 sm:px-8">
      <header className="max-w-3xl">
        <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-power">
          Worked example · nothing withheld
        </p>
        <h1 className="mt-3 text-3xl font-semibold leading-tight text-ghost sm:text-4xl">
          Read the deliverable before you pay for it.
        </h1>
        <p className="mt-4 text-mute">
          This is the complete output of a Capacity &amp; Density Envelope Study — the document,
          the walkthrough deck, the proposal, and the tables behind every number — run on a
          synthetic European colocation hall. Not a sample, not an extract. The whole thing.
        </p>
        <div className="mt-5 rounded border border-queue/40 bg-queue/10 p-4 text-sm text-ghost">
          <span className="font-mono text-[11px] uppercase tracking-[0.12em] text-queue">
            Synthetic reference data
          </span>
          <p className="mt-1 text-mute">
            The hall does not exist. Every figure is modelled from invented inputs and none is a
            measurement of a real site — which is exactly why we can publish it in full.
          </p>
        </div>
      </header>

      {best && gridOnly ? (
        <section className="mt-10 grid gap-3 sm:grid-cols-3">
          <Fig
            k="Deployable today"
            v={String(gridOnly.as_found.racks)}
            n={`racks · ${gridOnly.as_found.binding_name.toLowerCase()} binds first`}
          />
          <Fig
            k="On the grid connection alone"
            v={String(gridOnly.after_ladder.racks)}
            n="racks, after the costed ladder"
          />
          <Fig
            k="With behind-the-meter supply"
            v={String(best.after_ladder.racks)}
            n={
              best.time_to_power.weeks_to_full
                ? `racks · ${best.time_to_power.weeks_to_full.toFixed(0)} weeks, set by ${best.time_to_power.sets_the_date.toLowerCase()}`
                : "racks"
            }
          />
        </section>
      ) : null}

      <section className="mt-10 grid gap-4 md:grid-cols-3">
        <Card
          href="/reference/envelope_study.html"
          icon={<FileText className="h-4 w-4" />}
          title="The study"
          body="Thirteen sections: the answer, the headroom ladder, time to power, every architecture compared, sensitivity, economics, risks, and the provenance of every figure."
        />
        <Card
          href="/reference/walkthrough.html"
          icon={<Presentation className="h-4 w-4" />}
          title="The walkthrough deck"
          body="Nine slides from the same solved model, for the session with your engineering team. Arrow keys to advance; print to PDF to send."
        />
        <Card
          href="/reference/proposal.html"
          icon={<FileText className="h-4 w-4" />}
          title="The proposal"
          body="What a proposal looks like when the engine has already run: the binding constraint and the rack counts before the fee, and the data request in section three."
        />
      </section>

      <section className="mt-10 rounded border border-line bg-panel-2 p-6">
        <div className="flex items-start gap-3">
          <Table2 className="mt-0.5 h-4 w-4 shrink-0 text-power" />
          <div>
            <h2 className="text-lg font-semibold text-ghost">Check our arithmetic</h2>
            <p className="mt-2 max-w-3xl text-sm text-mute">
              The tables behind the document, as files your own engineers can open. Every headline
              quantity in <span className="font-mono text-ghost">provenance.csv</span> carries a
              digest and the digests it was derived from, so any number can be walked back to the
              assumption underneath it. A study you cannot check is a study you have to take on
              trust, and nobody sensible does that with a capital decision.
            </p>
            <div className="mt-4 flex flex-wrap gap-2">
              {[
                "working_files.zip",
                "working_files/scenarios.csv",
                "working_files/headroom_ladder.csv",
                "working_files/constraints.csv",
                "working_files/provenance.csv",
                "working_files/assumed_inputs.csv",
                "working_files/inputs.csv",
                "model_pack.json",
              ].map((f) => (
                <a
                  key={f}
                  href={`/reference/${f}`}
                  className="rounded border border-line px-3 py-1.5 font-mono text-xs text-mute hover:text-ghost"
                >
                  {f.replace("working_files/", "")}
                </a>
              ))}
            </div>
            {pack ? (
              <p className="mt-4 text-[11px] text-faint">
                This example runs at {Math.round(pack.intake.completeness * 100)}% intake
                completeness, with {pack.intake.gaps.length} input
                {pack.intake.gaps.length === 1 ? "" : "s"} still assumed — and the document names
                every one of them rather than hiding them in a caveat.
              </p>
            ) : null}
          </div>
        </div>
      </section>

      <section className="mt-10 flex flex-wrap items-center gap-4 rounded border border-line bg-panel-2 p-6">
        <div className="min-w-64 flex-1">
          <h2 className="text-lg font-semibold text-ghost">Now run it on your own hall.</h2>
          <p className="mt-1 text-sm text-mute">
            Seven numbers you already know, and the engine names the constraint that binds yours.
            Free, and it takes a minute.
          </p>
        </div>
        <Link
          href="/qualify"
          className="inline-flex items-center gap-2 rounded bg-power px-5 py-2.5 font-semibold text-ink"
        >
          Find the binding constraint <ArrowRight className="h-4 w-4" />
        </Link>
      </section>
    </main>
  );
}

function Fig({ k, v, n }: { k: string; v: string; n: string }) {
  return (
    <div className="rounded border border-line bg-panel-2 px-4 py-3">
      <p className="font-mono text-[10px] uppercase tracking-[0.14em] text-faint">{k}</p>
      <p className="mt-1 font-mono text-3xl font-semibold text-power">{v}</p>
      <p className="mt-1 text-xs text-faint">{n}</p>
    </div>
  );
}

function Card({
  href,
  icon,
  title,
  body,
}: {
  href: string;
  icon: React.ReactNode;
  title: string;
  body: string;
}) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noreferrer"
      className="panel flex flex-col p-5 transition-colors hover:border-power/50"
    >
      <span className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.14em] text-power">
        {icon}
        {title}
      </span>
      <p className="mt-3 text-sm text-mute">{body}</p>
      <span className="mt-auto pt-4 text-sm text-power">Open →</span>
    </a>
  );
}
